### ISSUE TITLE
SetUnderlineColor behaves differently in the VSCode integrated cmd/powershell than in external cmd/powershell

### ISSUE THREAD

**Issue by wamtnh** [ratatui/ratatui#1371]
I copied the hello ratatui tutorial from the website and then ran it in the VSCode integrated powershell. It ran fine. After that I tried to run it in an external powershell window and it rendered the frame and then errored with 'Error: Custom { kind: Other, error: "SetUnderlineColor not supported by winapi." }'.

## Screenshots
runs fine
![image](https://github.com/user-attachments/assets/7d8e1c4f-2359-48a6-893a-d06357fe85c7)

errors
![image](https://github.com/user-attachments/assets/afb97d04-1ab7-412a-b499-65df7ad95a96)

## Environment

- OS: Windows 10
- Crate version: 0.28.1
- Backend: crossterm

**Comment by joshka** [comment]
Thanks for reporting this.

I don't think any of the core Ratatui devs are Windows people (I haven't used it since about 2016 or so). So you might have to do some more investigation to look at what the difference in compilation / runtime is. Specifically compare cargo-tree in both terminals.
 
To workaround this, disable the default features of the Ratatui crate (which disables the underline-color feature), and enable just the crossterm feature.

**Comment by kdheepak** [comment]
I used it on Windows in my previous job but never tested it in powershell. It is possible that in powershell `crossterm` is using an old window api that doesn't support underline-color?

**Comment by wamtnh** [comment]
My (external) powershell apparently fails to enable vt processing while the VSCode one succeeds. Finding out what goes wrong is currently not in my interest and beyond my skill level, though I might try it sometime later if the issue persists.
