### ISSUE TITLE
GraphType::Bar does not work when y-axis minimum bound is > 0

### ISSUE THREAD

**Issue by Yomguithereal** [ratatui/ratatui#1391]
## Description

Because of the way `GraphType::Bar` is rendered [here](https://github.com/ratatui/ratatui/blob/main/src/widgets/chart.rs#L1048) (notice the `0.0`), a bar will never be drawn if the chart y-axis has a minimum bound > 0. I expect this is because a canvas line will not get drawn if some of its extremities are outside the canvas? In any case, replacing this zero with the axis' minimum y value should do the trick. I can submit a PR if you want.

## To Reproduce

Draw a chart with a dataset containing the points 1,1 2,2, 3,3 and `GraphType::Bar`.

## Expected behavior

Bars should be drawn. They are not :)

**Comment by joshka** [comment]
Hey there, apologies for there being no reply for this, it's been a busy few months. We've shuffled things around quite a bit as part of #1388, so the link doesn't resolve anymore. Do you recall which lines you were referring to?

There's a couple of recent issues that might fix this possibly:
- I fixed a canvas issue that had to do with how canvas points are translated to grid points (they now round to the nearest point instead of rounding towards 0).
- Another PR implemented the ability for lines to be clipped by the canvas region.

I wonder if you could give it a try against the main branch and link to a repo with a repro if this is still a problem?

**Comment by Yomguithereal** [comment]
@joshka I have tested multiple things that used not to work on the current main branch and I happily report that everything seems to be working now. I shall close this issue then :)

**Comment by joshka** [comment]
Glad to hear it :)
