### ISSUE TITLE
Scroll columns left and right using TableState

### ISSUE THREAD

**Issue by zaphar** [ratatui/ratatui#1472]
## Problem
It would be useful if you could scroll a table's columns not just the rows.

## Solution
Use selected_column in TableState to scroll by column. Not sure if this is feasible but it would be really helpful as a feature.

**Comment by orhun** [comment]
This is already possible via [`TableState::select_column`](https://docs.rs/ratatui/latest/ratatui/widgets/struct.TableState.html#method.select_column) if I'm not mistaking. Which version of Ratatui are you using?

**Comment by zaphar** [comment]
I'm using select column and it does not seem to work. I'm using v0.29.0.

**Comment by airblast-dev** [comment]
Would you be able to send an example of it not working?

**Comment by airblast-dev** [comment]
> This is already possible via [TableState::select_column](https://docs.rs/ratatui/latest/ratatui/widgets/struct.TableState.html#method.select_column) if I'm not mistaking.

Scrolling is actually not possible for the columns, only selecting and styling is possible. 

Joshka gave a pretty well explanation in a relevant issue https://github.com/ratatui/ratatui/issues/1250#issuecomment-2410674913 on why it isn't implemented. Originally I did implement things to make it scrollable, but scrapped it due to it making quite a bit assumptions on how the provided constraints are interpreted, resulting in usage that would be pretty inconsistent compared to the rest of the library.

**Comment by zaphar** [comment]
Ahh, I didn't see that issue when I was searching for prior examples. I did sort of figure it would be because figuring out correct scroll offset for a column would be non-trivial.

**Comment by joshka** [comment]
One thing you might be able to do to make this work is use tui-scrollview (or a similar manual technique) to render the table to a larger buffer and then copy the visible area to the main buffer. Then you'd need to work out the scroll offsets. It would be a pain, but would be possible. That's the best idea I can offer without changing some of the fundamental ways all the widgets work.

It would be definitely possible to write a table widget that could do horizontal scrolling and truncating partially visible columns, but I think there would be a huge amount of added complexity in the implementation. Because of that, I'd suggest that any work on this should be done outside of Ratatui before bringing it back in once proven. The process of ensuring that the code doesn't break all the existing code would be the most difficult part of this. Feel free to take the Table widget code and modify it as suits in your own app to give this a try (taking note of the MIT license requirements of course).

Because I don't see that there's much we can do on this one, I'd like to close this issue out, or we can also convert to a discussion if you'd prefer to keep it open to work though issues on this.

**Comment by zaphar** [comment]
For this *specific* use case I'm able to assume only Length constraints so I'm just creating a viewport abstraction that can compute whether the selected cell is in view and scroll appropriately so I can work around it.

It would obviously be nicer if it was supported directly but like most things it's possible to work around it.

**Comment by joshka** [comment]
There's some discussion relevant to this in https://github.com/ratatui/ratatui/discussions/1456

**Comment by zaphar** [comment]
I am comfortable with this being closed until a more comprehensive approach can be identified. I have a workable solution for myself in the meantime.
